- id: doorbell_light_flicker
  alias: "[Appartment] Flicker light on doorbell"
  description: ''
  trigger:
  - entity_id: binary_sensor.corridor_doorbell
    platform: state
    to: 'on'
  condition: []
  action:
  - service: script.lights_set_effect_if_onlne
    data:
      effect: "Doorbell"
  - service: notify.all_phones
    data:
      title: "Ding Dong!"
      message: "Someone's at the door!"
      data:
        channel: Doorbell
